# Generated by Django 2.2.5 on 2019-09-06 09:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0003_remove_keyworddata_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyworddata',
            name='preferential_treatment_word',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='keyworddata',
            name='qualifications_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
