# Generated by Django 2.2.5 on 2019-09-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0005_auto_20190906_1858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyworddata',
            unique_together={('date', 'keyword')},
        ),
    ]
